import { relations } from "drizzle-orm";
import { boolean, pgEnum, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

import { organization } from "@/lib/db/auth-schema";

/**
 * M9's commercial layer. Deliberately provider-neutral — which
 * payment processor is behind a subscription (Stripe, Shopify's
 * store checkout, or anything decided later) is an implementation
 * detail of `lib/billing/`'s provider adapter, never encoded into
 * column names here. Entitlement logic (`lib/billing/plans.ts`,
 * `lib/billing/usage.ts`) reads only `plan` and `status` and has no
 * idea a `provider` column exists (`DECISIONS.md`'s "payment
 * provider ≠ entitlement logic" entry). Two tables:
 *
 * `organization_billing` — one row per organization (created lazily,
 * defaulting to the `free` plan for any org that has never touched
 * billing), holding only what the configured provider itself has
 * told us via a verified webhook. `plan` and `status` are stored
 * separately because they answer different questions: `plan` is
 * *which* price the organization's subscription is for (survives a
 * lapse), `status` is whether that subscription is *currently*
 * entitled (`lib/billing/plans.ts`'s `isEntitledStatus`). Effective
 * entitlement is always `plan` gated by `status`, never `plan` alone
 * — a `pro` row with a `canceled` status is *not* Pro.
 *
 * `billing_webhook_event` — the idempotency ledger `lib/billing/`'s
 * webhook handler inserts into before doing anything else. Its
 * primary key is `(provider, provider_event_id)` — the provider's own
 * event id, which a provider can legitimately redeliver (a
 * documented possibility for both Stripe and Shopify), so a
 * redelivered event inserts nothing on the second attempt and the
 * handler returns success without reapplying any side effect. The
 * same `ON CONFLICT DO NOTHING`-as-serialization-point pattern
 * `changelog_notification` already uses (`DECISIONS.md` D8-004).
 */
export const billingPlan = pgEnum("billing_plan", ["free", "pro"]);

export const billingSubscriptionStatus = pgEnum("billing_subscription_status", [
  // No subscription has ever been created for this organization.
  "none",
  "active",
  "trialing",
  "past_due",
  "canceled",
  "incomplete",
  "incomplete_expired",
  "unpaid",
  "paused",
]);

export const organizationBilling = pgTable(
  "organization_billing",
  {
    organizationId: text("organization_id")
      .primaryKey()
      .references(() => organization.id, { onDelete: "cascade" }),
    // Which provider this organization's billing relationship is
    // with — null until the first Checkout attempt. Not a foreign key
    // to anything; just tags how to interpret the two provider-id
    // columns below.
    provider: text("provider"),
    // Null until the organization's first Checkout attempt creates a
    // provider-side customer record — set once, then reused for every
    // subsequent Checkout/portal session so an organization only ever
    // has one provider customer, never a fresh one per attempt.
    providerCustomerId: text("provider_customer_id"),
    providerSubscriptionId: text("provider_subscription_id"),
    plan: billingPlan("plan").notNull().default("free"),
    status: billingSubscriptionStatus("status").notNull().default("none"),
    currentPeriodEnd: timestamp("current_period_end"),
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    // Both nullable — Postgres allows any number of NULLs through a
    // unique index, so this only rejects two organizations somehow
    // sharing the same *non-null* provider id, never blocks the
    // common free-tier "both null" case.
    uniqueIndex("organization_billing_provider_customer_id_uidx").on(
      table.providerCustomerId,
    ),
    uniqueIndex("organization_billing_provider_subscription_id_uidx").on(
      table.providerSubscriptionId,
    ),
  ],
);

export const billingWebhookEvent = pgTable(
  "billing_webhook_event",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    provider: text("provider").notNull(),
    // The provider's own event id (e.g. Stripe's "evt_...") — never
    // generated by us. Unique per provider, not globally, since two
    // different providers' id spaces could theoretically collide.
    providerEventId: text("provider_event_id").notNull(),
    type: text("type").notNull(),
    processedAt: timestamp("processed_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("billing_webhook_event_provider_event_uidx").on(
      table.provider,
      table.providerEventId,
    ),
  ],
);

export const organizationBillingRelations = relations(
  organizationBilling,
  ({ one }) => ({
    organization: one(organization, {
      fields: [organizationBilling.organizationId],
      references: [organization.id],
    }),
  }),
);
