/**
 * Drizzle schema entrypoint.
 *
 * `auth-schema.ts` is generated by the Better Auth CLI
 * (`npx @better-auth/cli generate`) from `lib/auth/index.ts`'s config
 * (core auth + the `organization()` plugin) — do not hand-edit it;
 * regenerate it when the Better Auth config changes and re-review the
 * diff. Domain tables (Post, Vote, Comment, ... see
 * docs/M1_ARCHITECTURE_DECISION.md) are introduced in a future,
 * separately authorized milestone and will be added here alongside
 * the auth schema, not inside it.
 */
export * from "@/lib/db/auth-schema";
