/**
 * Drizzle schema entrypoint.
 *
 * `auth-schema.ts` is generated by the Better Auth CLI
 * (`npx @better-auth/cli generate`) from `lib/auth/index.ts`'s config
 * (core auth + the `organization()` plugin) — do not hand-edit it;
 * regenerate it when the Better Auth config changes and re-review the
 * diff.
 *
 * `feedback-schema.ts` is the hand-written domain schema (Board,
 * Post, Vote, Participant, Comment, Changelog — see
 * docs/M1_ARCHITECTURE_DECISION.md), introduced starting M4.
 *
 * `billing-schema.ts` is M9's commercial layer (Stripe-backed
 * subscription state, webhook idempotency) — see `lib/billing/`.
 */
export * from "@/lib/db/auth-schema";
export * from "@/lib/db/feedback-schema";
export * from "@/lib/db/billing-schema";
